/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package In_controller;

import bin.Photos;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import traitement.Chaleur;
import traitement.Image_d;
import traitement.Malik_Perona;
import traitement.Prewit;
import traitement.Sobel;
import javax.swing.JOptionPane;
import org.pdfsam.example.ProgressBar;
import traitement.AlvarezMorel;
import traitement.Blomgren;
import traitement.Derich;
import traitement.Nv_edp;
import traitement.Greyscale;
import traitement.Mcm;
import traitement.OsherRudin;
import traitement.Rotation;
import traitement.Sapiro;

/**
 *
 * @author Acer
 */
public class Interface_page extends javax.swing.JFrame {

    java.io.File origine, output;
    BufferedImage image = null, imgout = null;
    JLabel jlab = new JLabel();
    JLabel jlabg = new JLabel();
    int n = 0;

    /**
     * Creates new form Tp_interface
     */
    public Interface_page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        progressBar1 = new org.pdfsam.example.ProgressBar();
        progressBar2 = new org.pdfsam.example.ProgressBar();
        img_input = new javax.swing.JScrollPane();
        open_file = new javax.swing.JButton();
        clear_frame = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        img_input1 = new javax.swing.JScrollPane();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jRadioButton1 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        Ix = new javax.swing.JMenuItem();
        Iy = new javax.swing.JMenuItem();
        Ixx = new javax.swing.JMenuItem();
        Iyy = new javax.swing.JMenuItem();
        Sobel = new javax.swing.JMenuItem();
        Prewitt = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Chaleur = new javax.swing.JMenuItem();
        EMSS = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        Malek_Perona = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu6.setText("jMenu6");

        jMenu7.setText("jMenu7");

        jMenu8.setText("jMenu8");

        jMenuItem7.setText("jMenuItem7");

        jMenuItem9.setText("jMenuItem9");

        jMenuItem10.setText("jMenuItem10");

        jMenu10.setText("jMenu10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        img_input.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        img_input.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        img_input.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        img_input.setPreferredSize(new java.awt.Dimension(887, 502));

        open_file.setText("Select Photo");
        open_file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                open_fileActionPerformed(evt);
            }
        });

        clear_frame.setText("Clear frames");
        clear_frame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_frameActionPerformed(evt);
            }
        });

        img_input1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        img_input1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        img_input1.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        img_input1.setPreferredSize(new java.awt.Dimension(887, 502));
        img_input1.setViewportView(filler1);

        jRadioButton1.setText("Grey Scale");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jButton1.setText("Save result");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenu1.setText("Doctrine Classique");

        jMenu3.setText("Derive");

        Ix.setText("Ix");
        Ix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IxActionPerformed(evt);
            }
        });
        jMenu3.add(Ix);

        Iy.setText("Iy");
        Iy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IyActionPerformed(evt);
            }
        });
        jMenu3.add(Iy);

        Ixx.setText("Ixx");
        Ixx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IxxActionPerformed(evt);
            }
        });
        jMenu3.add(Ixx);

        Iyy.setText("Iyy");
        Iyy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IyyActionPerformed(evt);
            }
        });
        jMenu3.add(Iyy);

        jMenu1.add(jMenu3);

        Sobel.setText("Sobel");
        Sobel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SobelActionPerformed(evt);
            }
        });
        jMenu1.add(Sobel);

        Prewitt.setText("Prewitt");
        Prewitt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrewittActionPerformed(evt);
            }
        });
        jMenu1.add(Prewitt);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Analyse Multi-Echelle");

        Chaleur.setText("Chaleur");
        Chaleur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChaleurActionPerformed(evt);
            }
        });
        jMenu2.add(Chaleur);

        EMSS.setText("MCM");
        EMSS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EMSSActionPerformed(evt);
            }
        });
        jMenu2.add(EMSS);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Deffusion Anisotrope");

        Malek_Perona.setText("Malek_Perona");
        Malek_Perona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Malek_PeronaActionPerformed(evt);
            }
        });
        jMenu4.add(Malek_Perona);

        jMenuItem2.setText("Alvarez_Morel");
        jMenuItem2.setName("Alvarez_Morel"); // NOI18N
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuBar1.add(jMenu4);

        jMenu9.setText("Restauration du flou");

        jMenuItem3.setText("Osher_Rudin");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem3);

        jMenuBar1.add(jMenu9);

        jMenu5.setText("Restauration de couleur");

        jMenuItem4.setText("Sapiro");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem4);

        jMenuItem6.setText("Blomgren");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6);

        jMenuItem8.setText("Derich");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem8);

        jMenuItem11.setText("Edp_Proposé");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem11);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(open_file)
                        .addGap(62, 493, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addGap(286, 286, 286))
                            .addComponent(img_input, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(img_input1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(clear_frame)
                                .addGap(9, 9, 9)))
                        .addGap(100, 100, 100))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(126, 126, 126))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 262, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(248, 248, 248))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(open_file, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(img_input, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(img_input1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(clear_frame, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        img_input1.getAccessibleContext().setAccessibleName("img_output");
        img_input1.getAccessibleContext().setAccessibleDescription("img_output");

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void open_fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_open_fileActionPerformed
        JFileChooser jfc = new JFileChooser(); // create file chooser
        if (jfc.showOpenDialog(jLabel1) == JFileChooser.APPROVE_OPTION) {// open file and dislplay in frame
            origine = jfc.getSelectedFile();
            try {
                image = ImageIO.read(origine);
            } catch (IOException e) {
                System.err.println(e);
            }
            image = (BufferedImage) scaleImage(image, image.getWidth(), image.getHeight()); // resize with scaleImage()
        }
        ImageIcon icon = new ImageIcon(image);
        jlab.setIcon(icon); // set icon
        jlab.setHorizontalAlignment(JLabel.CENTER);// alignment
        img_input.getViewport().add(jlab);// add jLabel to inner frame
    }//GEN-LAST:event_open_fileActionPerformed

    private void clear_frameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_frameActionPerformed
        jlab.setIcon(null);
        jlabg.setIcon(null);
        origine = null;
        output = origine;
        image = null;
        Photos.setFile(null);
    }//GEN-LAST:event_clear_frameActionPerformed

    private void SobelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SobelActionPerformed
        Sobel sobel = new Sobel();
        Photos.setFile(origine);
        sobel.run();
        output = Photos.getFile();
        ImageIcon icon = new ImageIcon(creatImg(output));
        jlabg.setIcon(icon);
        jlabg.setHorizontalAlignment(jlabg.CENTER);
        img_input1.getViewport().add(jlabg);
    }//GEN-LAST:event_SobelActionPerformed

    private void PrewittActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrewittActionPerformed
        Prewit prewit = new Prewit();
        Photos.setFile(origine);
        prewit.run();
        output = Photos.getFile();
        ImageIcon icon = new ImageIcon(creatImg(output));
        jlabg.setIcon(icon);
        jlabg.setHorizontalAlignment(jlabg.CENTER);
        img_input1.getViewport().add(jlabg);
    }//GEN-LAST:event_PrewittActionPerformed

    private void ChaleurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChaleurActionPerformed
        Chaleur chaleur = new Chaleur();
        Photos.setFile(origine);
        String in = JOptionPane.showInputDialog("Nembre d'iteration");
        n = Integer.parseInt(in);
        if (n != 0) {
            chaleur.run(n);
            ProgressBar.launch(ProgressBar.class);
        }
        output = Photos.getFile();
        n = 0;
        ImageIcon icon = new ImageIcon(creatImg(output));
        jlabg.setIcon(icon);
        jlabg.setHorizontalAlignment(jlabg.CENTER);
        img_input1.getViewport().add(jlabg);
    }//GEN-LAST:event_ChaleurActionPerformed

    private void EMSSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EMSSActionPerformed
        // TODO add your handling code here:
        Mcm mcm = new Mcm();
        Photos.setFile(origine);
        String in = JOptionPane.showInputDialog("Nembre d'iteration");
        n = Integer.parseInt(in);
        if (n != 0) {
            mcm.run(n);
            ProgressBar.launch(ProgressBar.class);
        }
        output = Photos.getFile();
        n = 0;
        ImageIcon icon = new ImageIcon(creatImg(output));
        jlabg.setIcon(icon);
        jlabg.setHorizontalAlignment(jlabg.CENTER);
        img_input1.getViewport().add(jlabg);
    }//GEN-LAST:event_EMSSActionPerformed

    private void Malek_PeronaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Malek_PeronaActionPerformed
        // TODO add your handling code here:
        Malik_Perona malik_Perona = new Malik_Perona();
        Photos.setFile(origine);
        String in = JOptionPane.showInputDialog("Nembre d'iteration");
        n = Integer.parseInt(in);
        if (n != 0) {
            malik_Perona.anisodiff(1, n);
            ProgressBar.launch(ProgressBar.class);
        }
        output = Photos.getFile();
        n = 0;
        ImageIcon icon = new ImageIcon(creatImg(output));
        jlabg.setIcon(icon);
        jlabg.setHorizontalAlignment(jlabg.CENTER);
        img_input1.getViewport().add(jlabg);
    }//GEN-LAST:event_Malek_PeronaActionPerformed

    private void IxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IxActionPerformed
        Image_d image_d = new Image_d();
        Photos.setFile(origine);
        image_d.run(1);
        output = Photos.getFile();
        ImageIcon icon = new ImageIcon(creatImg(output));
        jlabg.setIcon(icon);
        jlabg.setHorizontalAlignment(jlabg.CENTER);
        img_input1.getViewport().add(jlabg);
    }//GEN-LAST:event_IxActionPerformed

    private void IyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IyActionPerformed
        // TODO add your handling code here:
        Image_d image_d = new Image_d();
        Photos.setFile(origine);
        image_d.run(2);
        output = Photos.getFile();
        ImageIcon icon = new ImageIcon(creatImg(output));
        jlabg.setIcon(icon);
        jlabg.setHorizontalAlignment(jlabg.CENTER);
        img_input1.getViewport().add(jlabg);
    }//GEN-LAST:event_IyActionPerformed

    private void IxxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IxxActionPerformed
        // TODO add your handling code here:
        Image_d image_d = new Image_d();
        Photos.setFile(origine);
        image_d.run(3);
        output = Photos.getFile();
        ImageIcon icon = new ImageIcon(creatImg(output));
        jlabg.setIcon(icon);
        jlabg.setHorizontalAlignment(jlabg.CENTER);
        img_input1.getViewport().add(jlabg);
    }//GEN-LAST:event_IxxActionPerformed

    private void IyyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IyyActionPerformed
        // TODO add your handling code here:
        Image_d image_d = new Image_d();
        Photos.setFile(origine);
        image_d.run(5);
        output = Photos.getFile();
        ImageIcon icon = new ImageIcon(creatImg(output));
        jlabg.setIcon(icon);
        jlabg.setHorizontalAlignment(jlabg.CENTER);
        img_input1.getViewport().add(jlabg);
    }//GEN-LAST:event_IyyActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        AlvarezMorel alvarezMorel = new AlvarezMorel();
        Photos.setFile(origine);
        String in = JOptionPane.showInputDialog("Nembre d'iteration");
        n = Integer.parseInt(in);
        if (n != 0) {
            alvarezMorel.run(n);
            ProgressBar.launch(ProgressBar.class);
        }
        output = Photos.getFile();
        n = 0;
        ImageIcon icon = new ImageIcon(creatImg(output));
        jlabg.setIcon(icon);
        jlabg.setHorizontalAlignment(jlabg.CENTER);
        img_input1.getViewport().add(jlabg);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        Greyscale greyscale = new Greyscale();
        Photos.setFile(origine);
        if (jRadioButton1.isSelected() == true) {
            greyscale.run();
            output = Photos.getFile();
        } else {
            output = origine;
        }
        ImageIcon icon = new ImageIcon(creatImg(output));
        jlab.setIcon(icon); // set icon
        jlab.setHorizontalAlignment(JLabel.CENTER);// alignment
        img_input.getViewport().add(jlab);//

    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        OsherRudin osherRudin = new OsherRudin();
        Photos.setFile(origine);
        String in = JOptionPane.showInputDialog("Nembre d'iteration");
        n = Integer.parseInt(in);
        if (n != 0) {
            osherRudin.run(n);
            ProgressBar.launch(ProgressBar.class);
        }
        output = Photos.getFile();
        n = 0;
        ImageIcon icon = new ImageIcon(creatImg(output));
        jlabg.setIcon(icon);
        jlabg.setHorizontalAlignment(jlabg.CENTER);
        img_input1.getViewport().add(jlabg);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        Sapiro sapiro = new Sapiro();
        Photos.setFile(origine);
        String in = JOptionPane.showInputDialog("Nembre d'iteration");
        n = Integer.parseInt(in);
        if (n != 0) {
            sapiro.run(n);;
            ProgressBar.launch(ProgressBar.class);
        }
        output = Photos.getFile();
        n = 0;
        ImageIcon icon = new ImageIcon(creatImg(output));
        jlabg.setIcon(icon);
        jlabg.setHorizontalAlignment(jlabg.CENTER);
        img_input1.getViewport().add(jlabg);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        Blomgren blomgren = new Blomgren();
        Photos.setFile(origine);
        String in = JOptionPane.showInputDialog("Nembre d'iteration");
        n = Integer.parseInt(in);
        if (n != 0) {
            blomgren.run(n);
            ProgressBar.launch(ProgressBar.class);
        }
        output = Photos.getFile();
        n = 0;
        ImageIcon icon = new ImageIcon(creatImg(output));
        jlabg.setIcon(icon);
        jlabg.setHorizontalAlignment(jlabg.CENTER);
        img_input1.getViewport().add(jlabg);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        Derich derich = new Derich();
        Photos.setFile(origine);
        String in = JOptionPane.showInputDialog("Nembre d'iteration");
        n = Integer.parseInt(in);
        if (n != 0) {
            derich.run(n);
            ProgressBar.launch(ProgressBar.class);
        }
        output = Photos.getFile();
        n = 0;
        ImageIcon icon = new ImageIcon(creatImg(output));
        jlabg.setIcon(icon);
        jlabg.setHorizontalAlignment(jlabg.CENTER);
        img_input1.getViewport().add(jlabg);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        Nv_edp eNv_edp = new Nv_edp();
        Photos.setFile(origine);
        String in = JOptionPane.showInputDialog("Nembre d'iteration");
        n = Integer.parseInt(in);
        if (n != 0) {
            eNv_edp.run(n);
            ProgressBar.launch(ProgressBar.class);
        }
        output = Photos.getFile();
        n = 0;
        ImageIcon icon = new ImageIcon(creatImg(output));
        jlabg.setIcon(icon);
        jlabg.setHorizontalAlignment(jlabg.CENTER);
        img_input1.getViewport().add(jlabg);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFrame parentFrame = new JFrame();
        output = Photos.getFile();

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Specify a file to save");
        int userSelection = fileChooser.showSaveDialog(parentFrame);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
           fileChooser.setCurrentDirectory(output); 
           output.getPath().replaceAll(output.getPath(), fileChooser.getCurrentDirectory().getPath());
           System.out.println("Save as file: " + output.getAbsolutePath());
}    }//GEN-LAST:event_jButton1ActionPerformed

    private Image scaleImage(Image img, int width, int height) {
        // resize if image is too large
        if (width > 420 && height > 315) {
            double scalew = 0;
            double scaleh = 0;
            if (width > 420) {
                scalew = (double) width / 420;
            }
            if (height > 315) {
                scaleh = (double) height / 315;
            }
            double scale = (scalew > scaleh ? scalew : scaleh);

            width = (int) (width / scale);
            height = (int) (height / scale);
        }
        BufferedImage resizedImage = new BufferedImage(width, height, BufferedImage.TYPE_INT_RGB);
        Graphics2D g2 = resizedImage.createGraphics();
        g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        g2.drawImage(img, 0, 0, width, height, null);
        g2.dispose();
        return resizedImage;
    }

    private Image creatImg(File file) {
        try {
            imgout = ImageIO.read(file);
        } catch (IOException e) {
            System.err.println(e);
        }
        imgout = (BufferedImage) scaleImage(imgout, imgout.getWidth(), imgout.getHeight()); // resize with scaleImage()
        return imgout;
    }

    private Image zoomImage(int zoomLevel, Image img) {
        BufferedImage in_image = (BufferedImage) img;
        int newWidth = 1, newHeight = 1, oldWidth = 1, oldHeight = 1;
        oldWidth = in_image.getWidth();
        oldHeight = in_image.getHeight();

        newHeight = oldHeight * zoomLevel;
        newWidth = oldWidth * zoomLevel;

        BufferedImage resizedImage = new BufferedImage(newWidth, newHeight, BufferedImage.TYPE_INT_RGB);
        Graphics2D g = resizedImage.createGraphics();
        in_image.getScaledInstance(newWidth, newHeight, Image.SCALE_SMOOTH);
        g.drawImage(in_image, 0, 0, newWidth, newHeight, null);
        g.dispose();
        return in_image;
    }

    /*  */
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface_page.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface_page.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface_page.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface_page.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface_page().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Chaleur;
    private javax.swing.JMenuItem EMSS;
    private javax.swing.JMenuItem Ix;
    private javax.swing.JMenuItem Ixx;
    private javax.swing.JMenuItem Iy;
    private javax.swing.JMenuItem Iyy;
    private javax.swing.JMenuItem Malek_Perona;
    private javax.swing.JMenuItem Prewitt;
    private javax.swing.JMenuItem Sobel;
    private javax.swing.JButton clear_frame;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JScrollPane img_input;
    private javax.swing.JScrollPane img_input1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JButton open_file;
    private org.pdfsam.example.ProgressBar progressBar1;
    private org.pdfsam.example.ProgressBar progressBar2;
    // End of variables declaration//GEN-END:variables
}
